language: node_js
node_js:
  - "8"
  addons:
    chrome: stable
    sudo: required
    before_script:
      - "sudo chwon root /opt/goole/chrome/chrome-sandbox"
      - "sudo chmod 4755 /opt/goole/chrome/chrome-sandbox"








;